services:
  # Backend service
  # - type: web
  #   name: aspira-backend
  #   env: node
  #   buildCommand: cd backend && npm install && npm run build
  #   startCommand: cd backend && npm start
  #   envVars:
  #     - key: NODE_ENV
  #       value: production
  #     - key: MONGODB_URI
  #       sync: false
  #     - key: EMAIL_SERVICE
  #       sync: false
  #     - key: EMAIL_USER
  #       sync: false
  #     - key: EMAIL_PASS
  #       sync: false

  - type: web
    name: aspira-webapp
    env: static
    rootDir: frontend
    buildCommand: npm install && npm run build
    staticPublishPath: dist
    domains:
      - aspira.life
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    envVars:
      - key: NODE_VERSION
        value: 18.17.0
      - key: NODE_ENV
        value: production
      - key: VITE_APP_ENV
        value: production
      - key: VITE_API_URL
        value: https://api.aspira.life
      - key: VITE_SITE_URL
        value: https://aspira.life
      - key: VITE_STRIPE_PUBLIC_KEY
        sync: false
      - key: VITE_GA_TRACKING_ID
        sync: false
