services:
  # Backend service
  - type: web
    name: aspira-backend
    env: node
    buildCommand: cd backend && npm install
    startCommand: cd backend && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 5001

  # Frontend static site
  - type: static-site
    name: aspira-frontend
    buildCommand: cd frontend && npm install && npm run build
    publishDir: frontend/dist
    headers:
      - path: /*
        name: Cache-Control
        value: no-cache
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
